### ISSUE TITLE
Client crashes when randomizing customization features for Worgen on the Death Knight class.

### ISSUE THREAD

**Issue by heyitsbench** [heyitsbench/mod-worgoblin#14]
This application has encountered a critical error:

ERROR #132 (0x85100084) Fatal Exception
Program: [Path]
Exception:        0xC0000005 (ACCESS_VIOLATION) at 0023:004EA273

The instruction at "0x004EA273" referenced memory at "0x00000010".
The memory could not be "read".

Press OK to terminate the application.

**Comment by benjymansy123** [comment]
Apparently happens with female worgen on other classes too. Different addresses I think, but not BLP related I don't think.

**Comment by bughero999** [comment]
Hi Bench,

First of all thank you for making & publishing this module. Even though it's not perfect it has saved me a ton of work, and couldn't have been easy to put together.

I know you're not maintaining it any more but in case you decide to again (or for anyone else reading this), I've narrowed down the cause of this crash to a few bad combos somewhere in charsections.dbc. If you delete the lines with ID 20197, and ID 20201 (that's WORGENFEMALESKIN00_03.blp and WORGENFEMALESKIN00_07.blp), you no longer get this crash. This disables two entire skin colors for worgen females, and I suspect the culprits are more specific combos enabled by those two, but for me that's good enough for now. If I get the motivation to narrow it down further I will update this post.

**Comment by heyitsbench** [comment]
> If you delete the lines with ID 20197, and ID 20201 (that's `WORGENFEMALESKIN00_03.blp` and `WORGENFEMALESKIN00_07.blp`), you no longer get this crash.

I suspected the issue was with CharSections, thanks for the find!

> This disables two entire skin colors for worgen females, and I suspect the culprits are more specific combos enabled by those two [...]

If you happen to find a solution that leaves these skin color options intact, feel free to submit a PR with that fix, and I'll be happy to merge it! If I manage to find time, I may try to correct it myself as well, but I am often busy these days unfortunately.

**Comment by bughero999** [comment]
Okay I found the specific issues. I don't really want to submit a PR myself right now because I have a bunch of other customizations in there and I don't really want to wipe clean to test it just yet. However, here are the fixes that worked for me:

1. Check out charsections.dbc ID 20254, it's currently blank, fill it out for face 05_03.

2. Check out charsections.dbc ID 20609, the RaceID is set to 15, should be 12.

Hope this helps! Thanks again for the mod!

**Comment by heyitsbench** [comment]
> However, here are the fixes that worked for me

I tested them out and they worked for me as well. Huge thanks for the fix!
