### ISSUE TITLE
racemask Question

### ISSUE THREAD

**Issue by Awixs777** [heyitsbench/mod-worgoblin#34]
Hi. Can you please tell me what is the value of this number? Goblin - 256, worgen - 2048, why is this value **4095** ?

UPDATE `playercreateinfo_skills` SET `racemask` = `racemask` + 256 WHERE `racemask` & 2;
UPDATE `playercreateinfo_skills` SET `racemask` = `racemask` + 2048 WHERE `racemask` & 1;
UPDATE `playercreateinfo_skills` SET `racemask` = **4095** WHERE `racemask` = 0;

**Comment by heyitsbench** [comment]
Value of 4095 is every playable race. To be honest, that query might not even be necessary, but that's what the 4095 means.
