### ISSUE TITLE
Strong weapon attack in druid mod-worgoblin 

### ISSUE THREAD

**Issue by MegaserverRU** [heyitsbench/mod-worgoblin#41]
Friends who can help? I have a problem in the mod-worgoblin mod, the power from weapons at the initial levels is greatly overestimated by hitting weapons at 8-9k What is wrong with this module? And are there any fixes?
![2023-01-06_11-53-59](https://user-images.githubusercontent.com/98691968/210968237-9312f076-f467-47cc-ac95-7884b45ac791.png)
![2023-01-06_11-55-08](https://user-images.githubusercontent.com/98691968/210968258-25adc44b-7402-4574-a69e-07dce74a7d76.png)

**Comment by heyitsbench** [comment]
This is likely related to a recent change with AC and the module regarding calculations for player stats. I'll take a look into it and see if I can reproduce it.

**Comment by MegaserverRU** [comment]
> This is likely related to a recent change with AC and the module regarding calculations for player stats. I'll take a look into it and see if I can reproduce it.

Test it, I will hope for a quick fix) I have provided you with a photo. Please let me know how to fix it

**Comment by heyitsbench** [comment]
Just tested from latest AC revision and a clean DB, [seems to be working as it should](https://user-images.githubusercontent.com/38561765/211058371-282561b9-8e64-4a09-a882-bf44ba7f4363.png). Would you be able to show me your `player_race_stats` table?
