### ISSUE TITLE
Creature model data.dbc however it is modified (unpacked to csv, or with dbc editor)

### ISSUE THREAD

**Issue by nyilasviktor0625** [heyitsbench/mod-worgoblin#43]
After writing to the CreatureModelData.dbc file attached to the source code, the game quits with a memory error after the worgen character no longer loads. I added an extra line that worked with the previous patches. What could be the problem, I have tried MyDBCediror and dbc wrapper software.
Thanks,

**Comment by heyitsbench** [comment]
The data for the DBCs have to be synchronized across server/client. If the server sends the client a display ID that the client can't find, the client dies. Please refer to the [Wowdev wiki article on client errors](https://wowdev.wiki/Client_Error_Analysis) if that's not the issue.

**Comment by nyilasviktor0625** [comment]
I put in the druid tree form, which is the default for all other races. The error code is as you linked:
"0x006DC86A" referenced memory at "0x00000004"

Unknown DisplayInfo %d specified for play race %d sex %d 
Please help me it is important

**Comment by nyilasviktor0625** [comment]
The DBC file is identical on both client and server side
