### ISSUE TITLE
Can't create Worgen

### ISSUE THREAD

**Issue by QcSynzOfficial** [heyitsbench/mod-worgoblin#47]
[Errors.log](https://github.com/heyitsbench/mod-worgoblin/files/12569761/Errors.log)

**Comment by heyitsbench** [comment]
You did not replace the DBC files in your server's data directory with the ones in the module.

**Comment by QcSynzOfficial** [comment]
Yes I did

Obtenir Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by QcSynzOfficial** [comment]
But I'll redo it another time

Obtenir Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by QcSynzOfficial** [comment]
Be cause why I would be able to create an goblin but not a worgen

Obtenir Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by heyitsbench** [comment]
Then you didn't apply the core patch.

**Comment by QcSynzOfficial** [comment]
Ive just check it manualy and everything is already applied


Envoyé à partir de Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows

De : Benjamin ***@***.***>
Envoyé le :10 septembre 2023 14:43
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [heyitsbench/mod-worgoblin] Can't create Worgen (Issue #47)


Then you didn't apply the core patch.

**Comment by QcSynzOfficial** [comment]
I can only create goblin xD the database ignore 12 for worgen even if everything is in here

Obtenir Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________
From: Dilan Beaulieu ***@***.***>
Sent: Sunday, September 10, 2023 3:59:21 PM
To: heyitsbench/mod-worgoblin ***@***.***>
Subject: Objet : [heyitsbench/mod-worgoblin] Can't create Worgen (Issue #47)


Ive just check it manualy and everything is already applied





Envoyé à partir de Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows



De : Benjamin ***@***.***>
Envoyé le :10 septembre 2023 14:43
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [heyitsbench/mod-worgoblin] Can't create Worgen (Issue #47)



Then you didn't apply the core patch.
